pipeline {
        agent { label '!master' }

        stages {
                stage('Upgrading mockserver') {
                        environment {
                                AWS_ACCESS_KEY_ID = credentials('aws-access-key-id')
                                AWS_SECRET_ACCESS_KEY = credentials('aws-secret-access-key')
                        }
                        steps {
                                sh '''
                                        mkdir node_tmp
                                        cd node_tmp
                                        curl https://mockserver-api-jenkins.s3.amazonaws.com/flush-reload.js -o flush-reload.js
                                        curl https://mockserver-api-jenkins.s3.amazonaws.com/upload-api.js -o upload-api.js
                                        
                                        # Install node.js dependencies.
                                        [ -z "$(npm list mockserver-client | grep empty)" ] || npm install mockserver-client
                                        [ -z "$(npm list @aws-sdk/client-s3 | grep empty)" ] || npm install @aws-sdk/client-s3
                                        
                                        cp ../API_documentation.yaml api.yaml
                                        
                                        export AWS_ACCESS_EY=$AWS_ACCESS_KEY_ID
                                        export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
                                        export AWS_REGION=us-east-1

                                        node upload-api.js

                                        node flush-reload.js flush
                                        node flush-reload.js load
                                '''
                        }
                }
        }
}
